services:
  his-prod:
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_TAG:-prod-latest}
    container_name: his-prod
    restart: always
    environment:
      NODE_ENV: production
      PORT: 4000
      DB_HOST: his-postgres
      DB_PORT: 5432
      DB_USER: his_prod
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: his_prod
    networks:
      # his-prod: private link to his-postgres
      # poms-prod: lets poms-api-prod and poms-nginx reach this service as his-prod:4000
      - his-prod
      - poms-prod
    healthcheck:
      test: ['CMD-SHELL', 'wget --no-verbose --tries=1 --spider http://localhost:4000/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  his-prod:
    external: true
  poms-prod:
    external: true
